### ISSUE TITLE
Все необязательные параметры генерируются с nullable:true

### ISSUE THREAD

**Issue by misha-rollun** [rollun-com/rollun-openapi#3]
**Пример манифеста (явно указан nullable:false):** 
```yaml
components:
  schemas:
    Tracker:
      type: object
      properties:
        public_url:
          type: string
          format: url
          nullable: false
          description: URL to a publicly-accessible html page that shows tracking details for this tracker
```
**Сгенерированный код (валидация в анотациях nullable=true):**
```php
<?php
declare(strict_types=1);

namespace Shipment\OpenAPI\V1\DTO;

use Articus\DataTransfer\Annotation as DTA;

/**
 */
class Tracker
{
    /**
     * URL to a publicly-accessible html page that shows tracking details for this tracker
     * @DTA\Data(field="public_url", nullable=true)
     * @DTA\Validator(name="Type", options={"type":"string"})
     * @var string
     */
    public $public_url;
}
```
