### ISSUE TITLE
Помилка валідації при використанні окремого enum об'єкту

### ISSUE THREAD

**Issue by maria-rollun** [rollun-com/rollun-openapi#31]
Якщо винести enum в окремий об'єкт, наприклад
```
    EntityType:
      type: string
      enum:
        - deal
        - client
        - offer
```
а потім використати його в параметрах запиту, наприклад
```
    parameters:
        - name: entityType
          in: path
          required: true
          schema:
            allOf:
              - $ref: '#/components/schemas/EntityType'
```
то валідація відбуватись не буде (пройде запит з будь яким значенням entityType).

Якщо ж просто вказати entityType як enum, наприклад
```
     parameters:
        - name: entityType
          in: path
          required: true
          schema:
            type: string
            enum:
              - deal
              - client
              - offer
```
то валідація буде відбуватись коректно, і будуть доступні тільки перелічені значення, а на решту буде падати помилка.
